app:
  ai:
    product:
      path: "${project.basedir}/fasttext_models/0110_appwiz_model.fasttext"
    publisher:
      path: "${project.basedir}/fasttext_models/0110_publisher_model_2.fasttext"
      
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/LicenseClassify
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  jpa:
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
